#include "muli3/convex_shape.h"
#include "muli3/distance.h"
#include "muli3/geometry.h"
#include "muli3/shape.h"

namespace muli3
{

static void FixFaceWinding(std::span<const Vec3> vertices, std::vector<Face>* faces, std::vector<int32>* indices)
{
    // After an arbitrary transform, especially one with negative scale, the face
    // orientation can flip. Re-orient all triangles so their normals point outward.
    Vec3 inside = Vec3::zero;
    for (const Vec3& vertex : vertices)
    {
        inside += vertex;
    }
    inside *= 1.0f / vertices.size();

    for (Face& face : *faces)
    {
        Vec3 a = vertices[(*indices)[face.vertexStart]];
        Vec3 b = vertices[(*indices)[face.vertexStart + 1]];
        Vec3 c = vertices[(*indices)[face.vertexStart + 2]];

        Vec3 normal = Cross(b - a, c - a);
        if (Dot(normal, inside - a) > 0.0f)
        {
            std::reverse(indices->begin() + face.vertexStart, indices->begin() + face.vertexStart + face.vertexCount);
        }
    }
}

static void ComputeFaceNormals(std::span<const Vec3> vertices, std::vector<Face>* faces, std::span<const int32> indices)
{
    // Faces are planar polygons, so the first three vertices determine the normal.
    for (Face& face : *faces)
    {
        Vec3 a = vertices[indices[face.vertexStart]];
        Vec3 b = vertices[indices[face.vertexStart + 1]];
        Vec3 c = vertices[indices[face.vertexStart + 2]];

        face.normal = Cross(b - a, c - a);
        face.normal.Normalize();
    }
}

ConvexShape::ConvexShape(std::span<const Vec3> inVertices, float inRadius, const Transform& transform)
    : Shape{ Shape::convex, inRadius }
{
    ComputeConvexHull(inVertices, &vertices, &indices, &faces);

    MuliAssert(vertices.size() >= 4);
    MuliAssert(faces.size() > 0);

    for (Vec3& vertex : vertices)
    {
        vertex = Mul(transform, vertex);
    }

    FixFaceWinding(vertices, &faces, &indices);
    ComputeFaceNormals(vertices, &faces, indices);

    MassData massData;
    ComputeMass(1.0f, &massData);
    center = massData.centerOfMass;
    volume = massData.mass;
}

ConvexShape::ConvexShape(
    std::span<const Vec3> inVertices,
    std::span<const int32> inIndices,
    std::span<const Face> inFaces,
    float inRadius,
    const Transform& transform
)
    : Shape{ Shape::convex, inRadius }
    , vertices{ inVertices.begin(), inVertices.end() }
    , indices{ inIndices.begin(), inIndices.end() }
    , faces{ inFaces.begin(), inFaces.end() }
{
    // Behavior is undefined if vertices/indices/faces do not describe a valid closed convex hull.

    MuliAssert(vertices.size() >= 4);
    MuliAssert(faces.size() > 0);
    MuliAssert(indices.size() > 0);
    MuliAssert(indices.size() <= std::numeric_limits<uint16>::max());
    for (const Face& face : faces)
    {
        MuliNotUsed(face);
        MuliAssert(face.vertexCount >= 3);
        MuliAssert(int32(face.vertexStart) + int32(face.vertexCount) <= int32(indices.size()));
    }

    for (Vec3& vertex : vertices)
    {
        vertex = Mul(transform, vertex);
    }

    FixFaceWinding(vertices, &faces, &indices);
    ComputeFaceNormals(vertices, &faces, indices);

    MassData massData;
    ComputeMass(1.0f, &massData);
    center = massData.centerOfMass;
    volume = massData.mass;
}

ConvexShape::ConvexShape(const ConvexShape& other, const Transform& transform)
    : ConvexShape(other.vertices, other.indices, other.faces, other.radius, transform)
{
}

void ConvexShape::ComputeMass(float density, MassData* outMassData) const
{
    MuliAssert(outMassData != nullptr);

    const auto Outer = [](const Vec3& a, const Vec3& b) { return Mat3(a * b.x, a * b.y, a * b.z); };
    const auto Mul = [](const Mat3& m, float s) { return Mat3(m.ex * s, m.ey * s, m.ez * s); };
    const auto Add = [](Mat3* a, const Mat3& b) { *a = *a + b; };

    float volume = 0.0f;
    Vec3 first = Vec3::zero;  // \int x dV
    Mat3 second = Mat3::zero; // \int x*x^T dV

    // Rounded convex shape is the Minkowski sum of the core hull and a sphere of radius r.
    //
    // Accumulate:
    //
    // V  = \int dV
    // M1 = \int x dV
    // M2 = \int x*x^T dV
    //
    // Then convert M2 to inertia at the end:
    //
    // I = \int (dot(x,x) Identity - x*x^T) dm = tr(M2) * Identity - M2
    //
    // The core hull is integrated as signed tetrahedra against the origin.
    // Rounded contributions are added as face slabs, edge cylindrical wedges,
    // and vertex spherical sectors generated by the convex radius.

    for (const Face& face : faces)
    {
        const Vec3& a = vertices[indices[face.vertexStart]];

        for (int32 i = 1; i + 1 < face.vertexCount; ++i)
        {
            // Core tetrahedron {O A B C}.
            //
            // x = u*a + v*b + w*c
            //
            // Standard tetrahedron domain:
            // u >= 0, v >= 0, w >= 0, u + v + w <= 1
            //
            // det = dot(a, cross(b, c))
            //
            // V = det / 6
            //
            // M1 = V * (a + b + c) / 4
            //
            // M2 diagonal example:
            // \int x^2 dV = det / 60 * (ax^2 + bx^2 + cx^2 + ax*bx + bx*cx + cx*ax)
            //
            // M2 off-diagonal example:
            // \int xy dV = det / 120 *
            //   (2(ax*ay + bx*by + cx*cy) + ax*by + ay*bx + ax*cy + ay*cx + bx*cy + by*cx)
            const Vec3& b = vertices[indices[face.vertexStart + i]];
            const Vec3& c = vertices[indices[face.vertexStart + i + 1]];

            // \int_{actual_tetra} f(p) dV =
            // \int_{standard_tetra} f(u a + v b + w c) det dudvdw

            // Jacobian determinant for transformation of standard tetra space to actual tetra space
            float det = Dot(a, Cross(b, c));
            float tetraVolume = det / 6.0f;

            volume += tetraVolume;

            first += (a + b + c) * (tetraVolume * 0.25f);

            float xx = det * (a.x * a.x + b.x * b.x + c.x * c.x + a.x * b.x + b.x * c.x + c.x * a.x) / 60.0f;
            float yy = det * (a.y * a.y + b.y * b.y + c.y * c.y + a.y * b.y + b.y * c.y + c.y * a.y) / 60.0f;
            float zz = det * (a.z * a.z + b.z * b.z + c.z * c.z + a.z * b.z + b.z * c.z + c.z * a.z) / 60.0f;

            float xy = det *
                       (2.0f * (a.x * a.y + b.x * b.y + c.x * c.y) + a.x * b.y + a.y * b.x + a.x * c.y + a.y * c.x + b.x * c.y +
                        b.y * c.x) /
                       120.0f;
            float yz = det *
                       (2.0f * (a.y * a.z + b.y * b.z + c.y * c.z) + a.y * b.z + a.z * b.y + a.y * c.z + a.z * c.y + b.y * c.z +
                        b.z * c.y) /
                       120.0f;
            float zx = det *
                       (2.0f * (a.z * a.x + b.z * b.x + c.z * c.x) + a.z * b.x + a.x * b.z + a.z * c.x + a.x * c.z + b.z * c.x +
                        b.x * c.z) /
                       120.0f;

            Add(&second, Mat3{ Vec3{ xx, xy, zx }, Vec3{ xy, yy, yz }, Vec3{ zx, yz, zz } });
        }
    }

    if (volume < 0.0f)
    {
        volume = -volume;
        first = -first;
        second = Mat3{ -second.ex, -second.ey, -second.ez };
    }

    if (volume < epsilon)
    {
        outMassData->mass = 0.0f;
        outMassData->centerOfMass = Vec3::zero;
        outMassData->inertia = Mat3::zero;
        return;
    }

    float r = radius;
    float r2 = r * r;
    float r3 = r2 * r;
    float r4 = r2 * r2;
    float r5 = r4 * r;

    // Face slabs.
    //
    // Extrude each core face outward along its normal n by radius r:
    //
    // x = p + t*n
    //
    // p is on the face triangle T
    // t in [0, r]
    //
    // V = r * A
    //
    // M1 = r * \int_T p dA + (r^2 / 2) * A * n
    //
    // M2 = r * \int_T pp^T dA
    //    + (r^2 / 2) * ((\int_T p dA)n^T + n(\int_T p dA)^T)
    //    + (r^3 / 3) * A * nn^T
    //
    // Triangle integrals:
    //
    // \int_T p dA = A * (a + b + c) / 3
    // \int_T pp^T dA = A / 12 * (aa^T + bb^T + cc^T + ss^T), where s = a+b+c
    for (int32 faceIndex = 0; faceIndex < int32(faces.size()); ++faceIndex)
    {
        const Face& face = faces[faceIndex];
        Vec3 n = face.normal;
        const Vec3& a = vertices[indices[face.vertexStart]];

        for (int32 i = 1; i + 1 < face.vertexCount; ++i)
        {
            const Vec3& b = vertices[indices[face.vertexStart + i]];
            const Vec3& c = vertices[indices[face.vertexStart + i + 1]];

            float area = 0.5f * Length(Cross(b - a, c - a));
            Vec3 sum = a + b + c;
            Vec3 triangleFirst = sum * (area / 3.0f);
            Mat3 triangleSecond = Mul(Outer(a, a) + Outer(b, b) + Outer(c, c) + Outer(sum, sum), area / 12.0f);

            volume += area * r;
            first += triangleFirst * r + n * (area * r2 * 0.5f);
            Add(&second, Mul(triangleSecond, r));
            Add(&second, Mul(Outer(triangleFirst, n) + Outer(n, triangleFirst), r2 * 0.5f));
            Add(&second, Mul(Outer(n, n), area * r3 / 3.0f));
        }
    }

    struct EdgeInfo
    {
        int32 a;
        int32 b;
        int32 face0;
        int32 face1;
    };

    std::vector<EdgeInfo> edges;
    for (int32 faceIndex = 0; faceIndex < int32(faces.size()); ++faceIndex)
    {
        const Face& face = faces[faceIndex];
        for (int32 i = 0; i < face.vertexCount; ++i)
        {
            int32 a = indices[face.vertexStart + i];
            int32 b = indices[face.vertexStart + (i + 1) % face.vertexCount];
            int32 minIndex = Min(a, b);
            int32 maxIndex = Max(a, b);

            bool found = false;
            for (EdgeInfo& edge : edges)
            {
                if (edge.a == minIndex && edge.b == maxIndex)
                {
                    edge.face1 = faceIndex;
                    found = true;
                    break;
                }
            }

            if (!found)
            {
                edges.push_back(EdgeInfo{ minIndex, maxIndex, faceIndex, -1 });
            }
        }
    }

    // Edge cylindrical wedges.
    //
    // Each core edge is swept by the circular sector between its two adjacent face normals.
    //
    // x = p(s) + q
    //
    // p(s) = p0 + e*s, s in [0, L]
    // q = rho * (u*cos(phi) + v*sin(phi))
    // rho in [0, r], phi in [0, angle]
    //
    // u = n0
    // v = normalize(n1 - n0 * dot(n0, n1))
    //
    // Sector integrals:
    //
    // A_q = angle * r^2 / 2
    //
    // Q1 = \int_sector q dA
    //    = r^3 / 3 * (u*sin(angle) + v*(1 - cos(angle)))
    //
    // Q2 = \int_sector qq^T dA
    //    = r^4 / 4 * [
    //        uu^T * (angle/2 + sin(angle)cos(angle)/2)
    //      + vv^T * (angle/2 - sin(angle)cos(angle)/2)
    //      + (uv^T + vu^T) * sin^2(angle)/2
    //      ]
    //
    // Segment integrals:
    //
    // S1 = \int_0^L p(s) ds
    //    = L * (p0 + p1) / 2
    //
    // S2 = \int_0^L p(s)p(s)^T ds
    //    = L / 3 * (p0p0^T + p1p1^T) + L / 6 * (p0p1^T + p1p0^T)
    //
    // Wedge integrals:
    //
    // V  = L * A_q
    // M1 = A_q * S1 + L * Q1
    // M2 = A_q * S2 + S1*Q1^T + Q1*S1^T + L * Q2
    for (const EdgeInfo& edgeInfo : edges)
    {
        if (edgeInfo.face1 < 0)
        {
            continue;
        }

        Vec3 p0 = vertices[edgeInfo.a];
        Vec3 p1 = vertices[edgeInfo.b];
        Vec3 edge = p1 - p0;
        float length = edge.Normalize();
        if (length <= epsilon)
        {
            continue;
        }

        Vec3 n0 = faces[edgeInfo.face0].normal;
        Vec3 n1 = faces[edgeInfo.face1].normal;
        float angle = std::acos(Clamp(Dot(n0, n1), -1.0f, 1.0f));
        if (angle <= epsilon)
        {
            continue;
        }

        Vec3 u = n0;
        Vec3 v = NormalizeSafe(n1 - n0 * Dot(n0, n1));
        if (Length2(v) <= epsilon)
        {
            continue;
        }

        float sectorArea = 0.5f * angle * r2;
        Vec3 sectorFirst = (u * std::sin(angle) + v * (1.0f - std::cos(angle))) * (r3 / 3.0f);

        float sinAngle = std::sin(angle);
        float cosAngle = std::cos(angle);
        float uu = angle * 0.5f + sinAngle * cosAngle * 0.5f;
        float vv = angle * 0.5f - sinAngle * cosAngle * 0.5f;
        float uv = sinAngle * sinAngle * 0.5f;
        Mat3 sectorSecond = Mul(Outer(u, u), uu * r4 * 0.25f) + Mul(Outer(v, v), vv * r4 * 0.25f) +
                            Mul(Outer(u, v) + Outer(v, u), uv * r4 * 0.25f);

        Vec3 segmentFirst = (p0 + p1) * (0.5f * length);
        Mat3 segmentSecond =
            Mul(Outer(p0, p0) + Outer(p1, p1), length / 3.0f) + Mul(Outer(p0, p1) + Outer(p1, p0), length / 6.0f);

        volume += length * sectorArea;
        first += segmentFirst * sectorArea + sectorFirst * length;
        Add(&second, Mul(segmentSecond, sectorArea));
        Add(&second, Outer(segmentFirst, sectorFirst) + Outer(sectorFirst, segmentFirst));
        Add(&second, Mul(sectorSecond, length));
    }

    for (int32 vertexIndex = 0; vertexIndex < int32(vertices.size()); ++vertexIndex)
    {
        std::vector<Vec3> incidentNormals;
        for (int32 faceIndex = 0; faceIndex < int32(faces.size()); ++faceIndex)
        {
            const Face& face = faces[faceIndex];
            bool incident = false;
            for (int32 i = 0; i < face.vertexCount; ++i)
            {
                if (indices[face.vertexStart + i] == vertexIndex)
                {
                    incident = true;
                    break;
                }
            }

            if (!incident)
            {
                continue;
            }

            bool duplicate = false;
            for (const Vec3& normal : incidentNormals)
            {
                if (Dot(normal, face.normal) > 1.0f - 1e-4f)
                {
                    duplicate = true;
                    break;
                }
            }

            if (!duplicate)
            {
                incidentNormals.push_back(face.normal);
            }
        }

        if (incidentNormals.size() < 3)
        {
            continue;
        }

        Vec3 axis = Vec3::zero;
        for (const Vec3& normal : incidentNormals)
        {
            axis += normal;
        }
        axis.Normalize();
        if (Length2(axis) <= epsilon)
        {
            continue;
        }

        Vec3 tangent0 = Cross(Abs(axis.x) < 0.9f ? x_axis : y_axis, axis);
        tangent0.Normalize();
        Vec3 tangent1 = Cross(axis, tangent0);

        std::sort(incidentNormals.begin(), incidentNormals.end(), [&](const Vec3& a, const Vec3& b) {
            float angleA = std::atan2(Dot(a, tangent1), Dot(a, tangent0));
            float angleB = std::atan2(Dot(b, tangent1), Dot(b, tangent0));
            return angleA < angleB;
        });

        float orientation = 0.0f;
        for (int32 i = 0; i < int32(incidentNormals.size()); ++i)
        {
            const Vec3& a = incidentNormals[i];
            const Vec3& b = incidentNormals[(i + 1) % incidentNormals.size()];
            orientation += Dot(Cross(a, b), axis);
        }
        if (orientation < 0.0f)
        {
            std::reverse(incidentNormals.begin(), incidentNormals.end());
        }

        float solidAngle = 0.0f;
        Vec3 sphereFirst = Vec3::zero;
        Mat3 sphereSecond = Mat3::zero;

        // Vertex spherical sector.
        //
        // The vertex normal cone intersects the unit sphere as a convex spherical polygon R.
        //
        // With direction u and radius rho:
        //   q = rho * u
        //
        //   int dV      = int_R int_0^r rho^2 d rho dOmega = Omega * r^3 / 3
        //   int q dV    = (int_R u dOmega)      * r^4 / 4
        //   int qq^T dV = (int_R uu^T dOmega)   * r^5 / 5
        //
        // Omega is the solid angle of R.  The code sums it as a fan of spherical
        // triangles around the averaged normal axis:
        //
        //   Omega += 2 * atan2(axis dot (a x b), 1 + axis dot a + a dot b + b dot axis)
        //
        // For a positively oriented great-circle edge a -> b:
        //   g = normalize(a x b), theta = acos(a dot b)
        //
        //   int_R u dOmega = 1/2 * sum(theta * g)
        //
        // The second directional moment uses the spherical Green identity:
        //   int_R uu^T dOmega = Omega / 3 * I + 1/6 * sum(g e^T + e g^T)
        //
        // where e = int_edge u ds = tan(theta / 2) * (a + b).
        for (int32 i = 0; i < int32(incidentNormals.size()); ++i)
        {
            const Vec3& a = incidentNormals[i];
            const Vec3& b = incidentNormals[(i + 1) % incidentNormals.size()];
            Vec3 cross = Cross(a, b);
            float sinTheta = cross.Normalize();
            float cosTheta = Clamp(Dot(a, b), -1.0f, 1.0f);
            if (sinTheta <= epsilon)
            {
                continue;
            }

            float theta = std::atan2(sinTheta, cosTheta);
            solidAngle += 2.0f * std::atan2(Dot(axis, Cross(a, b)), 1.0f + Dot(axis, a) + Dot(a, b) + Dot(b, axis));
            sphereFirst += cross * (0.5f * theta);

            Vec3 edgeIntegral = (a + b) * std::tan(theta * 0.5f);
            Add(&sphereSecond, Mul(Outer(cross, edgeIntegral) + Outer(edgeIntegral, cross), 1.0f / 6.0f));
        }

        if (solidAngle <= epsilon)
        {
            continue;
        }

        Add(&sphereSecond, Mul(Mat3{ identity }, solidAngle / 3.0f));

        Vec3 p = vertices[vertexIndex];
        float sectorVolume = solidAngle * r3 / 3.0f;
        Vec3 relativeFirst = sphereFirst * (r4 / 4.0f);
        Mat3 relativeSecond = Mul(sphereSecond, r5 / 5.0f);

        volume += sectorVolume;
        first += p * sectorVolume + relativeFirst;
        Add(&second, Mul(Outer(p, p), sectorVolume));
        Add(&second, Outer(p, relativeFirst) + Outer(relativeFirst, p));
        Add(&second, relativeSecond);
    }

    Mat3 inertia{
        Vec3{ second.ey.y + second.ez.z, -second.ey.x, -second.ez.x },
        Vec3{ -second.ex.y, second.ex.x + second.ez.z, -second.ez.y },
        Vec3{ -second.ex.z, -second.ey.z, second.ex.x + second.ey.y },
    };

    outMassData->mass = density * volume;
    outMassData->centerOfMass = first / volume;
    outMassData->inertia = Mat3(inertia.ex * density, inertia.ey * density, inertia.ez * density);
}

void ConvexShape::ComputeAABB(const Transform& transform, AABB* outAABB) const
{
    MuliAssert(outAABB != nullptr);

    Vec3 min = Mul(transform, vertices[0]);
    Vec3 max = min;

    for (int32 i = 1; i < int32(vertices.size()); ++i)
    {
        Vec3 v = Mul(transform, vertices[i]);
        min = Min(min, v);
        max = Max(max, v);
    }

    float scaledRadius = radius * Max(Abs(transform.s.x), Max(Abs(transform.s.y), Abs(transform.s.z)));
    Vec3 r{ scaledRadius, scaledRadius, scaledRadius };
    *outAABB = AABB{ min - r, max + r };
}

int32 ConvexShape::GetSupport(const Vec3& localDir) const
{
    // The hull is stored explicitly as vertices, so support is a simple max dot scan.
    int32 index = 0;
    float maxValue = Dot(localDir, vertices[0]);

    for (int32 i = 1; i < int32(vertices.size()); ++i)
    {
        float value = Dot(localDir, vertices[i]);
        if (value > maxValue)
        {
            index = i;
            maxValue = value;
        }
    }

    return index;
}

Face ConvexShape::GetFeaturedFace(const Transform& transform, const Vec3& dir) const
{
    // Contact clipping wants the face whose normal is most aligned with the query
    // direction in local space.
    Vec3 localDir = transform.q.RotateInv(dir);
    int32 index = 0;
    float maxValue = Dot(faces[0].normal, localDir);

    for (int32 i = 1; i < int32(faces.size()); ++i)
    {
        float value = Dot(faces[i].normal, localDir);
        if (value > maxValue)
        {
            index = i;
            maxValue = value;
        }
    }

    Face face = faces[index];
    face.normal = transform.q.Rotate(face.normal);

    return face;
}

bool ConvexShape::TestPointLocal(const Vec3& q) const
{
    // For a closed convex polyhedron, the point is inside iff it lies behind every
    // outward face plane.
    for (int32 i = 0; i < int32(faces.size()); ++i)
    {
        if (Dot(faces[i].normal, q - vertices[indices[faces[i].vertexStart]]) > 0.0f)
        {
            return false;
        }
    }

    return true;
}

bool ConvexShape::TestPoint(const Transform& transform, const Vec3& q) const
{
    Vec3 localQ = MulT(transform, q);
    if (TestPointLocal(localQ))
    {
        return true;
    }

    Vec3 closest = GetClosestPointLocal(localQ);
    return Dist2(localQ, closest) <= radius * radius;
}

Vec3 ConvexShape::GetClosestPointLocal(const Vec3& q) const
{
    if (TestPointLocal(q))
    {
        return q;
    }

    // Outside the hull, the closest point must lie on one of the surface triangles.
    Vec3 closest = vertices[0];
    float minDistance2 = max_float;

    for (const Face& face : faces)
    {
        const Vec3& a = vertices[indices[face.vertexStart]];

        for (int32 i = 1; i + 1 < face.vertexCount; ++i)
        {
            const Vec3& b = vertices[indices[face.vertexStart + i]];
            const Vec3& c = vertices[indices[face.vertexStart + i + 1]];

            Vec3 p = ClosestPointVsTriangle(q, a, b, c);
            float distance2 = Dist2(q, p);
            if (distance2 < minDistance2)
            {
                closest = p;
                minDistance2 = distance2;
            }
        }
    }

    return closest;
}

Vec3 ConvexShape::GetClosestPoint(const Transform& transform, const Vec3& q) const
{
    Vec3 localQ = MulT(transform, q);
    Vec3 closest = GetClosestPointLocal(localQ);
    Vec3 delta = localQ - closest;

    float distance = delta.Normalize();
    if (distance <= radius)
    {
        return q;
    }

    return Mul(transform, closest + delta * radius);
}

bool ConvexShape::RayCast(const Transform& transform, const RayCastInput& input, RayCastOutput* output) const
{
    RayCastInput localInput = input;
    localInput.from = MulT(transform, input.from);
    localInput.to = MulT(transform, input.to);

    Vec3 p1 = localInput.from;
    if (TestPointLocal(p1))
    {
        return false;
    }

    Vec3 d = localInput.to - localInput.from;

    float near = 0.0f;
    float far = input.maxFraction;
    int32 index = -1;

    for (int32 i = 0; i < int32(faces.size()); ++i)
    {
        Vec3 normal = faces[i].normal;
        Vec3 v = vertices[indices[faces[i].vertexStart]];

        float numerator = Dot(normal, v - p1);
        float denominator = Dot(normal, d);

        if (Abs(denominator) <= epsilon)
        {
            if (numerator < 0.0f)
            {
                return false;
            }
        }
        else
        {
            if (denominator < 0.0f && numerator < near * denominator)
            {
                near = numerator / denominator;
                index = i;
            }
            else if (denominator > 0.0f && numerator < far * denominator)
            {
                far = numerator / denominator;
            }
        }

        if (far < near)
        {
            return false;
        }
    }

    if (index < 0 || near < 0.0f || near > input.maxFraction)
    {
        return false;
    }

    output->fraction = near;
    output->normal = transform.q.Rotate(faces[index].normal);
    return true;
}

} // namespace muli3
